version: "3.2"

services:
  moralis-ropsten:
    image: nginx
    volumes:
      - ./moralis-ropsten.conf:/etc/nginx/nginx.conf

  moralis-ropsten-archive:
    image: nginx
    volumes:
      - ./moralis-ropsten-archive.conf:/etc/nginx/nginx.conf

  load-balancer:
    image: nginx
    volumes:
      - ./load-balancer.conf:/etc/nginx/nginx.conf
    ports:
      - "3333:8080"
    deploy:
      replicas: 1
    depends_on:
      - moralis-ropsten
      - moralis-ropsten-archive
