version: "3.2"

services:
  balancer:
    image: go-balancer
    volumes:
       - ./tokens.txt:/root/tokens.txt

  infura-ropsten:
    image: nginx
    volumes:
      - ./server.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - HOST=https://ropsten.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161

  # ----------

  infura-kovan:
    image: nginx
    volumes:
      - ./server.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - HOST=https://kovan.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161

  # ----------

  alchemy-mainnet:
    image: nginx
    volumes:
      - ./server.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - HOST=https://eth-mainnet.alchemyapi.io/v2/xWjz3Gf53QIWM80eqYkYWXFAeGU3uU1R

  infura-mainnet:
    image: nginx
    volumes:
      - ./server.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - HOST=https://mainnet.infura.io/v3/e1e3689e3d834d5eb4ec3d95eb4dda50

  infura-mainnet-2:
    image: nginx
    volumes:
      - ./server.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - HOST=https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161

  # ----------

  rpc-fantom:
    image: nginx
    volumes:
      - ./server.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - HOST=https://rpc.ftm.tools

  rpc-avalanche:
    image: nginx
    volumes:
      - ./server.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - HOST=https://api.avax.network/ext/bc/C/rpc

  # ----------
  dataseed-binance:
    image: nginx
    volumes:
      - ./server.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - HOST=https://bsc-dataseed1.defibit.io

  bsc-rpc:
    image: nginx
    volumes:
      - ./server.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - HOST=https://BSCRPC.com


  dataseed-binance-2:
    image: nginx
    volumes:
      - ./server.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - HOST=https://bsc-dataseed3.defibit.io

  dataseed-binance-3:
    image: nginx
    volumes:
      - ./server.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - HOST=https://bsc-dataseed4.ninicoin.io


  # infstones-binance:
  #   image: nginx
  #   volumes:
  #     - ./server.conf.template:/etc/nginx/templates/default.conf.template
  #   environment:
  #     - HOST=https://api.infstones.io/bsc/mainnet/4da2819f44164c9aa380776f54916e18

  # infstones-binance-2:
  #   image: nginx
  #   volumes:
  #     - ./server.conf.template:/etc/nginx/templates/default.conf.template
  #   environment:
  #     - HOST=https://api.infstones.io/bsc/mainnet/4bec45c91f9c45b18f3c1374c712f3d8

  # infstones-binance-3:
  #   image: nginx
  #   volumes:
  #     - ./server.conf.template:/etc/nginx/templates/default.conf.template
  #   environment:
  #     - HOST=https://api.infstones.io/bsc/mainnet/86a9159d4af94251b7dd76a4bc4783a2

  # infstones-binance-archive:
  #   image: nginx
  #   volumes:
  #     - ./server.conf.template:/etc/nginx/templates/default.conf.template
  #   environment:
  #     - HOST=https://api.infstones.io/bsc-archive/mainnet/e9be5e2a5eb14432b7452dafaaa0cc8b

  # infstones-binance-archive-2:
  #   image: nginx
  #   volumes:
  #     - ./server.conf.template:/etc/nginx/templates/default.conf.template
  #   environment:
  #     - HOST=https://api.infstones.io/bsc-archive/mainnet/e45486f13c42414c862bb350e5c3ea58

  # infstones-binance-archive-3:
  #   image: nginx
  #   volumes:
  #     - ./server.conf.template:/etc/nginx/templates/default.conf.template
  #   environment:
  #     - HOST=https://api.infstones.io/bsc-archive/mainnet/4de36d988da7464da946a3042b71a5ed

  # dataseed-binance-1:
  #   image: nginx
  #   volumes:
  #     - ./server.conf.template:/etc/nginx/templates/default.conf.template
  #   environment:
  #     - HOST=https://bsc-dataseed1.ninicoin.io

  # dataseed-binance-1-2:
  #   image: nginx
  #   volumes:
  #     - ./server.conf.template:/etc/nginx/templates/default.conf.template
  #   environment:
  #     - HOST=https://bsc-dataseed1.defibit.io



  # ----------

  binance-testnet:
    image: nginx
    volumes:
      - ./server.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - HOST=https://data-seed-prebsc-1-s1.binance.org:8545

  # ----------

  moralis-polygon:
    image: nginx
    volumes:
      - ./server.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - HOST=http://go-balancer:3030/$token/polygon/mainnet


  rpc-polygon:
    image: nginx
    volumes:
      - ./server.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - HOST=https://polygon-rpc.com

  alchemy-polygon:
    image: nginx
    volumes:
      - ./server.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - HOST=https://polygon-mainnet.g.alchemy.com/v2/YW8khK4qms8RrrfKMfdKennC3_DsLdV3

  # ----------
  

  rpc-polygon-mumbai:
    image: nginx
    volumes:
      - ./server.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - HOST=https://rpc-mumbai.maticvigil.com

  alchemy-polygon-mumbai:
    image: nginx
    volumes:
      - ./server.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - HOST=https://polygon-mumbai.g.alchemy.com/v2/VbZ3Eaoud1snZdOP9nhqGvniVw09EznN

  # ----------

  load-balancer:
    image: nginx
    volumes:
      - ./load-balancer.conf:/etc/nginx/nginx.conf
    ports:
      - "3333:8080"
    depends_on:
      - balancer

      - infura-ropsten
      - infura-kovan

      - alchemy-mainnet
      - infura-mainnet
      - infura-mainnet-2

      - bsc-rpc
      - dataseed-binance
      - dataseed-binance-2
      - dataseed-binance-3

      - rpc-fantom
      - rpc-avalanche


      # - infstones-binance
      # - infstones-binance-2
      # - infstones-binance-3
      # - infstones-binance-archive
      # - infstones-binance-archive-2
      # - infstones-binance-archive-3
 
      # - dataseed-binance-1
      # - dataseed-binance-1-2
  
      - binance-testnet

      - moralis-polygon
      - rpc-polygon
      - alchemy-polygon

      - rpc-polygon-mumbai
      - alchemy-polygon-mumbai
    deploy:
      replicas: 1
